apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: scnfs-secrets
  namespace: scnfs-demo
## No data hardcoded here, obviously, so it is not shared with the world.
## Before you deploy the application, you need to provide the authorization details
## Create two files
## And then run the following command to update the secret with the data
## kubectl create secret generic scnfs-secrets \ 
##    --save-config --dry-run=client \
##    --from-file=./geoip2.account-id \
##    --from-file=./geoip2.license-key \
##    --from-file=./hotelbeds.api-key \
##    --from-file=./hotelbeds.shared-secret \
##    -o yaml | kubectl apply -f -
##
## Thanks, Janos Lenart! (https://stackoverflow.com/questions/45879498/how-can-i-update-a-secret-on-kubernetes-when-it-is-generated-from-a-file)
