apiVersion: v1
kind: Service
metadata:
  labels:
    app: airport-finder
  name: airport-finder
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: airport-finder
  type: ClusterIP