apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: hb-hotel-finder
  name: hb-hotel-finder
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hb-hotel-finder
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hb-hotel-finder
    spec:
      containers:
      - image: {{ .Values.dockerhub.repo }}/hb-hotel-finder:{{ .Values.dockerhub.version.hb_hotel_finder }}
        imagePullPolicy: {{ .Values.dockerhub.policy }}
        name: hb-hotel-finder
        ports:
        - containerPort: 8888
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /manage/health
            port: 8888
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8888
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 30
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secrets
        env: 
          -
            name: docker-secret.bind-path
            value: /etc/secrets
      volumes:
        - name: secret-volume
          secret:
            secretName: scnfs-secrets
