apiVersion: v1
kind: Service
metadata:
  labels:
    app: hb-hotel-finder
  name: hb-hotel-finder
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: hb-hotel-finder
  type: ClusterIP